name: Build, Test, and Commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Commit built files
        if: success() # Only commit if the previous steps were successful
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add lib
          git commit -m "Add built files" || echo "No changes to commit"

      - name: Push changes
        if: success() # Only push if the previous steps were successful
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git push origin main
